'''
Given: A DNA string s of length at most 1000 nt.

Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s


Sample Dataset:
AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC

Sample Output:
20 12 17 21

'''


s = "ATCAAGGGACAGATTCGCCTAACTCAGTGCTCCCTTAGTTAAGGAGCGATCGCCCTCTCACGCAGCATTCGCTCAACATCCGTCAGGGTCGACCTAGTACGAACAGCACATGCCGAGCGACGGGGGTCTGAAGGCCAGGAGTTTTCTTAGCGCGCGCTCTTCTTCTCACAGAGGGGGAAGGACCGCTTGGTCTATCGCCGCCCGCCGCCACCCTGAGCAGAGCTCAAGTGACTCTCCCTGGGGCGCCTTTTTCCGGTTACCTCAGTATGAGTTTACTAGGCTTCCCAGACGCTTAATGACAGGCAGTTAGAGATACTTACGCAATGAGAGGGCCTATGAGGCAGGTACGAGTGGTATCACAACGCCGGGCCCTGATAGGGCGAGACTGTCGCAGCTATACAGGAGGCCCGTTTAGATAGTAGCACCGACTATGTATCTTTTGCGGACTTACAAGGATTATTGCTGATCTCGTTCGGGCGCTGTTTTGAATCTCTAAAAAGGCGAAGGGCATCAGGCTGTCATACAGTTTCACCACTAGATAAGGTGTCTACGTGTATATGTTCCTGGCTAAGTCTTGCGTGCTTTGGAGGTGATTGTCCCTGCACTCGACATTATTCGCTATTTCTTAGAGAGCTTATGGCTTAAGCATAAACCTCGATCTATGTGCATACCTTTTGCTAAGGGGGGTCCGTATTAACCTCGTAAGTAATAGGACTTGAGATCTTGAAAGACGACAGCTAGAGGTGTAGGCTGAGTAACGGCGACCTAACCTCGTTACCGTCCGGCCGGCTAGTCCAGTAGAGAACTGAAGACTGCGTTTGACTAGCATCCAGTGTATACTCATTTAGACGGAAGATGTA"

a = 0
c = 0
g = 0
t = 0

for base in s:
    if base == 'A':
        a +=1
    elif base == 'C':
        c += 1
    elif base == 'G':
        g += 1
    elif base == 'T':
        t += 1
        
print(a,c,g,t)